// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.API.DbContexts;

#nullable disable

namespace MinimalApi.API.Migrations
{
    [DbContext(typeof(PratoDbContext))]
    partial class PratoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("IngredientePrato", b =>
                {
                    b.Property<int>("IngredientesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PratosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientesId", "PratosId");

                    b.HasIndex("PratosId");

                    b.ToTable("IngredientePrato");

                    b.HasData(
                        new
                        {
                            IngredientesId = 1,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 2,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 3,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 4,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 5,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 6,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 7,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 8,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 14,
                            PratosId = 1
                        },
                        new
                        {
                            IngredientesId = 9,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 19,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 11,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 12,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 13,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 2,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 21,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 8,
                            PratosId = 2
                        },
                        new
                        {
                            IngredientesId = 1,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 12,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 17,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 14,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 2,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 16,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 23,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 8,
                            PratosId = 3
                        },
                        new
                        {
                            IngredientesId = 1,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 18,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 16,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 20,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 22,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 2,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 21,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 8,
                            PratosId = 4
                        },
                        new
                        {
                            IngredientesId = 24,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 10,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 23,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 2,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 12,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 18,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 14,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 20,
                            PratosId = 5
                        },
                        new
                        {
                            IngredientesId = 13,
                            PratosId = 5
                        });
                });

            modelBuilder.Entity("MinimalApi.API.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Carne de Vaca"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cebola"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cerveja Escura"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fatia de Pão Integral"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Mostarda"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Chicória"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Maionese"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Vários Temperos"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Mexilhões"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Aipo"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Batatas Fritas"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Tomate"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Extrato de Tomate"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Folha de Louro"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Cenoura"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Alho"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Vinho Tinto"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Leite de Coco"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Gengibre"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Pimenta Malagueta"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Tamarindo"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Peixe Firme"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Pasta de Gengibre e Alho"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Garam Masala"
                        });
                });

            modelBuilder.Entity("MinimalApi.API.Entities.Prato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pratos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ensopado Flamengo de Carne de Vaca com Chicória"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mexilhões com Batatas Fritas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ragu alla Bolognese"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rendang"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Masala de Peixe"
                        });
                });

            modelBuilder.Entity("IngredientePrato", b =>
                {
                    b.HasOne("MinimalApi.API.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApi.API.Entities.Prato", null)
                        .WithMany()
                        .HasForeignKey("PratosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
